version: '3'
services:
  postgres:
    container_name: postgresdb
    image: postgres:latest
    build:
      dockerfile: Dockerfile
      context: ./backend/src/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  graphql:
    container_name: graphql
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - PIRVATE_KEY=${PIRVATE_KEY}
    ports:
      - "8081:8081"